### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alterlleo** [AlessiaRinaldi/2D-plotter-manipulator#1]
- [ ] test pwm pull up
- [ ] check if the blue servo needs 5V pwm
- [ ] hierarchy between telegram bot and uart script
